apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app-2
  # annotations:
  #   argocd.argoproj.io/tracking-id: kubevela-test-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: crccheck/hello-world
        port: 8000
      traits:
        - type: ingress-1-20
          properties:
            domain: localhost
            http:
              "/": 8000