apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubevela-app

resources:
- app.yaml
- nginx.yaml


configMapGenerator:
- name: nginx
  files:
  - nginx.conf
  
generatorOptions:
  disableNameSuffixHash: true

# patches:
#   - patch: |-
#       apiVersion: apps/v1
#       kind: Deployment
#       metadata:
#         name: argocd-server
#       spec:
#         template:
#           spec:
#             containers:
#               - name: argocd-server
#                 command:
#                   - argocd-server
#                   - --insecure