apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: vela-nginx
  # annotations:
  #   argocd.argoproj.io/tracking-id: kubevela-test-app
spec:
  components:
    - name: nginx
      type: webservice
      properties:
        image: nginx:alpine
        port: 80
      traits:
        - type: ingress-1-20
          properties:
            class: "traefik"
            domain: localhost
            http:
              "/nginx": 80